---
- name: Prepare basic environment for database replication between two servers.
  hosts: http
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - tools
    - nfs
    - php
    - nginx
    - mysql-client
