---
- name: Create directory for nfs
  file: path=/nfsData state=directory mode=777
  ignore_errors: True

- name: Configure nfs entry in /etc/fstab dir
  lineinfile: dest=/etc/fstab line="10.0.0.200:/data    /nfsData    nfs    defaults,ro    0 0"
