---
- name: Install php
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php5
    - curl
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-imagick
    - php5-fpm
    - php-apc
    - php5-memcached
    - php5-mysql
